import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Sparkles, Check, Info } from 'lucide-react';
export const RecommendationCard = ({ recommendation, onApply, isApplying = false, }) => {
    const { id, title, description, category, expectedImpact, businessValue, confidenceLevel, priority, status, tags } = recommendation;
    const categoryColors = {
        'High Impact': 'bg-rose-50 text-rose-700 border-rose-100',
        'Quick Win': 'bg-amber-50 text-amber-700 border-amber-100',
        'Ongoing': 'bg-sky-50 text-sky-700 border-sky-100',
    };
    // High (Red), Medium (Orange), Low (Blue)
    const priorityColors = {
        High: 'bg-rose-50 text-[#EF4444] border border-rose-100',
        Medium: 'bg-amber-50 text-[#F59E0B] border border-amber-100',
        Low: 'bg-blue-50 text-[#3B82F6] border border-blue-100',
    };
    const isImplemented = status === 'Implemented';
    return (_jsxs("div", { className: "bg-white rounded-[20px] border border-[#E5E7EB] p-6 shadow-sm hover:shadow-md transition-all duration-200 flex flex-col justify-between group h-full", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-start justify-between gap-4", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: `text-[10px] font-bold px-2.5 py-0.5 rounded-full border ${categoryColors[category] || 'bg-slate-50 text-slate-700 border-slate-100'}`, children: category }), _jsxs("span", { className: `text-[10px] uppercase font-extrabold tracking-wider px-2 py-0.5 rounded ${priorityColors[priority]}`, children: [priority, " Priority"] })] }), _jsx("div", { className: "flex items-center gap-1.5 text-xs font-bold text-emerald-600 bg-emerald-50 px-2.5 py-0.5 rounded-full", children: _jsxs("span", { children: [confidenceLevel, "% Conf"] }) })] }), _jsx("h3", { className: "text-base font-bold text-[#111827] mt-4 group-hover:text-[#7C3AED] transition-colors duration-150", children: title }), _jsx("p", { className: "text-xs text-[#6B7280] mt-2 line-clamp-3 leading-relaxed", children: description }), _jsxs("div", { className: "mt-4 grid grid-cols-2 gap-3 bg-slate-50/50 p-3.5 rounded-[12px] border border-slate-100", children: [_jsxs("div", { children: [_jsx("span", { className: "text-[9px] font-bold text-[#9CA3AF] uppercase tracking-wider", children: "Expected Impact" }), _jsx("p", { className: "text-xs font-extrabold text-[#10B981] mt-0.5", children: expectedImpact })] }), _jsxs("div", { children: [_jsx("span", { className: "text-[9px] font-bold text-[#9CA3AF] uppercase tracking-wider", children: "Business Value" }), _jsx("p", { className: "text-xs font-extrabold text-[#111827] mt-0.5", children: businessValue })] })] }), _jsx("div", { className: "flex flex-wrap gap-1.5 mt-4", children: tags.map((tag) => (_jsxs("span", { className: "text-[10px] font-semibold text-[#9CA3AF] bg-slate-100/50 px-2.5 py-0.5 rounded-full", children: ["#", tag] }, tag))) })] }), _jsxs("div", { className: "mt-6 pt-4 border-t border-slate-50 flex items-center justify-between", children: [_jsxs("span", { className: "text-xs text-[#6B7280]", children: ["Status: ", _jsx("strong", { className: isImplemented ? 'text-[#10B981]' : 'text-[#6B7280]', children: status })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("button", { type: "button", className: "h-[36px] px-3 bg-white border border-[#E5E7EB] hover:bg-slate-50 text-[#111827] rounded-[8px] text-xs font-semibold cursor-pointer transition-colors flex items-center gap-1", children: [_jsx(Info, { className: "w-3.5 h-3.5 text-[#6B7280]" }), "Learn More"] }), onApply && (_jsx("button", { onClick: () => onApply(id), disabled: isImplemented || isApplying, className: `h-[36px] px-4 rounded-[8px] text-xs font-bold border transition-all duration-200 cursor-pointer flex items-center gap-1.5 ${isImplemented
                                    ? 'bg-emerald-50 text-[#10B981] border-emerald-100 cursor-not-allowed'
                                    : 'bg-[#7C3AED] text-white border-[#7C3AED] hover:bg-[#6D28D9] shadow-sm shadow-purple-100 hover:shadow'}`, children: isImplemented ? (_jsxs(_Fragment, { children: [_jsx(Check, { className: "w-3.5 h-3.5" }), "Applied"] })) : isApplying ? (_jsxs(_Fragment, { children: [_jsx("div", { className: "w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" }), "Applying..."] })) : (_jsxs(_Fragment, { children: [_jsx(Sparkles, { className: "w-3.5 h-3.5" }), "Implement"] })) }))] })] })] }));
};
