from pydantic import BaseModel, Field
from typing import Dict, Any

class AgentQueryRequest(BaseModel):
    query: str = Field(..., description="Natural language query for the BI Assistant chatbot")

class AgentQueryResponse(BaseModel):
    query: str = Field(..., description="Original query received")
    route_called: str = Field(..., description="Calculated API route used to solve query")
    raw_data: Dict[str, Any] = Field(..., description="Raw output generated by the calculation engine")
    response: str = Field(..., description="Natural language response synthesized by LLM")
